# Ingress template for the application

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "go-web-app-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: {{ include "go-web-app-chart.fullname" . }}
               port:
                 number: {{ .Values.service.port }}