# CI/CD pipeline using GitHub Actions for go-web-app

name: CI/CD

# Run the workflow on pushes to the main branch, excluding certain paths
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  # Build and Test Job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      # Build the Go application
      - name: Build
        working-directory: ./go-web-app
        run: go build -o go-web-app main.go

      # Run tests
      - name: Test
        working-directory: ./go-web-app
        run: go test ./...

  # Code Quality Job using golangci-lint
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2
        working-directory: ./go-web-app

  # Docker Build and Push Job
  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to DockerHub using secrets
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./go-web-app
          file: ./go-web-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.run_id }}

  # Helm Chart Tag Update Job
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      # Update the Docker image tag in the Helm chart's values.yaml file
      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/go-web-app-chart/values.yaml

      # Commit and push the changes to the Helm chart
      - name: Commit and push changes
        run: |
          git config --global user.email "kamalakannan075@yahoo.com"
          git config --global user.name "kamalkkn"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push

