apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: debug-container
      image: kamalakannan72/go-web-app:v1
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]

